name: tryapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^0.13.3  # Moved from dev_dependencies to dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash_image.jpg
    - assets/jsonfiles/bottom_bar.json
    - assets/jsonfiles/adding_a_grower.json
    - assets/jsonfiles/adding_a_farm.json
    - assets/jsonfiles/privacy_policy.json
    - assets/jsonfiles/terms_conditions.json
    - assets/images/plant.png
